//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITech.Security.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Models = new HashSet<Model>();
            this.Operations = new HashSet<Operation>();
            this.Roles = new HashSet<Role>();
            this.Sections = new HashSet<Section>();
            this.Views = new HashSet<View>();
        }
    
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Model> Models { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<View> Views { get; set; }
    }
}
