//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITech.Security.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public View()
        {
            this.RoleViews = new HashSet<RoleView>();
        }
    
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int SectionId { get; set; }
        public string Description { get; set; }
        public bool SameWindow { get; set; }
        public Nullable<int> ZIndex { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<RoleView> RoleViews { get; set; }
        public virtual Section Section { get; set; }
    }
}
